import type { Metadata } from "next";
import localFont from "next/font/local";
import Navigation from "@/app/componets/navigation";
import "./globals.css";

const myfont = localFont({
  src: [
    {
      path: "./fonts/BlackOpsOne-Regular.ttf",
      weight: "900",
      style: "normal",
    },
  ]
})

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <header className={`p-10 bg-black text-white text-xl ${myfont.className}`} >
        {/* className= 'p-10 bg-black text-white text-xl' */}
          <Navigation />
        </header>
        <div className={myfont.className}>
        {children}
        </div>
        <footer className="p-10 bg-black text-white text-center">
          Created by Santino Giordnao
        </footer>
      </body>
    </html>
  );
}
